const EURMTL_CODE = 'EURMTL';
const EURMTL_ISSUER =
  'GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V';
const MTLAP_CODE = 'MTLAP';
const MTLAP_ISSUER = 'GCNVDZIHGX473FEI7IXCUAEXUJ4BGCKEMHF36VYP5EMS7PX2QBLAMTLA';
const HORIZON_URL = 'https://horizon.stellar.org/';
const COUNCIL_DELEGATE_TAG = 'mtla_c_delegate';
const COUNCIL_READY_VALUE = 'ready';

exports.EURMTL_CODE = EURMTL_CODE;
exports.EURMTL_ISSUER = EURMTL_ISSUER;
exports.MTLAP_CODE = MTLAP_CODE;
exports.MTLAP_ISSUER = MTLAP_ISSUER;
exports.HORIZON_URL = HORIZON_URL;
exports.COUNCIL_DELEGATE_TAG = COUNCIL_DELEGATE_TAG;
exports.COUNCIL_READY_VALUE = COUNCIL_READY_VALUE;
